name: jagadeesh
on: workflow_dispatch
jobs:
   github:
      runs-on: ubuntu-latest
      steps:
        - name: complile the code
          run: echo "one"

         - name: test the code 
           run: mkdir two
